### ISSUE TITLE
Style guide architecture

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-styleguide#11]
As a contributor with the proper permissions, I should be able to write markdown to update design guidelines for usage of our components in the Reaction Commerce design system. As well as have the ability to add images or embed videos. 

As a reaction engineer, I should be able to easily add and update components for documentation of our React UI components. 

As a contributor to Reaction Commerce, both core contributors or community contributors, I should be able to view a style guide that has - 

- design guidelines for components, 
- visual representation of our components with properties, 
- the ability to select between our most common usages (i.e. buttons types)
- ability to copy react code 

As a design director, I should be able to add static pages such as Reaction Commerce design principles (now) and color, typography, and illustration guidelines (in the future).

**Comment by machikoyasuda** [comment]
Closing this in favor or component library
